### ISSUE TITLE
PCSA Web Prototype

### ISSUE THREAD

**Issue by MeepyMay** [systers/PCSA-web#1]
[PCSA Web basic prototype.pdf](https://github.com/systers/PCSA-web/files/177166/PCSA.Web.basic.prototype.pdf)

**Comment by AkankshaBodhankar** [comment]
@MeepyMay  Has the webapp include the reuirements given in this 
https://github.com/systers/PCSA-Android/issues/49

**Comment by MeepyMay** [comment]
Yes @AkankshaBodhankar 

The Web App should show the same content and design as the mobile apps.

**Comment by PrabhanshuAttri** [comment]
@MeepyMay Hey which language/framework are you looking for?
