### ISSUE TITLE
Deployment of Web App on the Server.

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/PCSA-web#24]
The web app is not deployed anywhere for a live demo. When a new user visits, the person needs to download the zip or clone the repository and run it on local host, which makes it cumbersome. Deployment on a web server will ease the access and anyone can keep a track of implemented modules easily. @AkankshaBodhankar

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui  Thank you for mentioning about it !There is a deployed version of this web app.
However, the database hasn't been integrated due few reasons and it's still in progress that's why we have not made it public yet.

**Comment by AkankshaBodhankar** [comment]
You can always look for new bugs in the app. Only the gci tasks are currently unavailable however, you can claim the other issues. @fatimarafiqui Keep contributing!

**Comment by fatimarafiqui** [comment]
I was wondering if I could see the live website on the web server. @AkankshaBodhankar

**Comment by AkankshaBodhankar** [comment]
Okay sure you can! But, the database is not up yet.Here http://54.215.183.60/

**Comment by fatimarafiqui** [comment]
Is there any way I can help you with the database, or any other thing that keeps it pending. That will help the bug finding easier as well.

**Comment by AkankshaBodhankar** [comment]
That's not under my control. The app is deployed under the peace corps server. However, you can run it on your local machine and try to find the bugs.

**Comment by fatimarafiqui** [comment]
Okay, I got that.
