### ISSUE TITLE
PCSA Web: Proposed UI

### ISSUE THREAD

**Issue by PrabhanshuAttri** [systers/PCSA-web#3]
I am designed a mockup and created a login page ( [Dummy Login Page](http://prabhanshu.com/gsoc/systers/) )
 to show how material UI can improvise the user experience and subsequently contribute to the success of this project.

[PCSAFirstAide-ProposedUI.pdf](https://github.com/systers/PCSA-web/files/187958/PCSAFirstAide-ProposedUI.pdf)

**Comment by PrabhanshuAttri** [comment]
User Interface is still very basic, gives a feel of a dummy website while a lot of work has been done. Someone can enhance the UI. Let me know if you need my help. @rosariorobinson @MeepyMay

**Comment by AkankshaBodhankar** [comment]
The user interface has been made according to the PCSA Android. Huge modification in the design is not possible. However if you can suggest basic changes feel free to add an issue and we will let you know if that works. Thank you !

**Comment by PrabhanshuAttri** [comment]
In that case, we can also improve the android app design. Moving fast and breaking things might help the community as a whole. I am contributing to other communities as well. They welcome code and design refactoring, and major improvements with open arms.

As aptly said by Benjamin Franklin
> "Without continual growth and progress, such words as improvement, achievement, and success have no meaning."

Correct me if I am wrong or mistaken. @willingc @tapasweni-pathak @valeriecodes

**Comment by AkankshaBodhankar** [comment]
@PrabhanshuAttri You can contact @MeepyMay for the same! She can help you with this :-)

**Comment by AkankshaBodhankar** [comment]
As the three apps of FirstAide ios, web and android have the same design this can be suggested for all the three. Generally, we keep such issues as suggestion and forward it to the peace corps. Meanwhile you can start a conversation in the mailing list

**Comment by PrabhanshuAttri** [comment]
@AkankshaBodhankar could you please re-open this issue as you have added the tag 'suggestion'.

**Comment by AkankshaBodhankar** [comment]
Suggestions are generally forwarded to the peace corps. They decide the requirements. The suggestions will be forwarded to the peace corps and will be reopened if they get approved.
